---
- hosts: leaf:spine:edge
  connection: local
  gather_facts: no

  tasks:
  - include_role:
      name: netops
      tasks_from: vlan_deploy
    vars:
      interface: "{{ item }}"
      vlan_id: "{{ vlan_id }}"
      vlan_description: "{{ vlan_description }}"
    with_items: "{{ pod_interconnects.keys() }}"
