---
- hosts: leaf:spine:edge
  connection: local
  gather_facts: no

  tasks:
  - name: initialize interconnect ports
    include_role:
      name: netops
      tasks_from: trunk_port
    vars:
      interface: "{{ item }}"
    with_items: "{{ pod_interconnects.keys() }}"
