---
- hosts: leaf:spine:edge
  connection: local
  gather_facts: no
  serial: 2

  tasks:
  - include_role:
      name: netops
      tasks_from: default_trunk
    vars:
      interface: "{{ item }}"
    with_items: "{{ pod_interconnects.keys() }}"
