---
- hosts: leaf:spine:edge
  connection: local
  gather_facts: no

  tasks:
  - include_role:
      name: netops
      tasks_from: init_trunk
    vars:
      interface: "{{ item }}"
    with_items: "{{ pod_interconnects.keys() }}"
