---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - nxos_config:
      lines: "{{ pod_interconnects[item].lines.split('\n') }}"
      parents: "interface {{item}}"
      save_when: modified
      diff_against: running
      provider:
        timeout: 400
    with_items: "{{ pod_interconnects.keys() }}"
