---
- hosts: leaf:spine:edge
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        tower_api_inventory_id: "{{ lookup('env', 'INVENTORY_ID') }}"
      tags: online

    - nxos_command:
        commands:
          - show cdp neighbors detail
          - show run interface
      register: show_commands
      tags: online

    - include_role:
        name: network-cli
        tasks_from: parse
      vars:
        filename: ./parser/cdp_neighbors.yml
        contents: "{{ show_commands.stdout.0 }}"
      tags: online

    - include_role:
        name: network-cli
        tasks_from: parse
      vars:
        filename: ./parser/cdp_neighbors.yml
        contents: "{{ lookup('file', './tests/'+inventory_hostname+'-0.txt') }}"
      tags: offline

    - debug: var=neighbors_list
      tags: debug

    - include_role:
        name: network-cli
        tasks_from: parse
      vars:
        filename: ./parser/int_config.yml
        contents: "{{ show_commands.stdout.1 }}"
      tags: online

    - include_role:
        name: network-cli
        tasks_from: parse
      vars:
        filename: ./parser/int_config.yml
        contents: "{{ lookup('file', './tests/'+inventory_hostname+'-1.txt') }}"
      tags: debug

    - debug: var=interfaces
      tags: debug

    - set_fact:
        pod_interconnects : "{{ pod_interconnects | default({}) | combine({item.local_port : interfaces[item.local_port] | combine({'neighbor' : item.remote_device | regex_replace('\\(.+', '')})}) }}"
      with_items: "{{ neighbors_list }}"
      when: item.local_port in interfaces.keys()
      tags:
        - offline
        - online

    - debug: var=pod_interconnects
      tags: debug

    - set_fact:
        active_interfaces: "{{ active_interfaces | default({}) | combine(item) }}"
      with_items: "{{ interfaces }}"
      when:
        - item not in pod_interconnects.keys()
        - item.lines.0 != 'shutdown'
      tags:
        - offline
        - online

    - debug: var=active_interfaces
      tags: debug

    - include_role:
        name: tower-api
        tasks_from: update-vars
      vars:
        update_vars: "{'pod_interconnects' : {{pod_interconnects}} }"
      delegate_to: localhost
      tags:
        - offline
        - online
