---
- nxos_facts:

- assert:
    that: "vlan_id in ansible_facts.vlan_list"
  msg: "VLAN does not exist. Please deploy first"
  
- name: "access VLAN {{ vlan_id }} on {{ interface }}"
  nxos_config:
    before: "default interface {{ interface }}"
    lines:
      - description Access Port
      - switchport
      - switchport mode access
      - “switchport access vlan {{ vlan_id }}”
    parents: "interface {{ interface }}"
    provider:
      timeout: 400
  when: interface not in pod_interconnects.keys()
