---
- nxos_facts:

- name: Check for VLAN
  assert:
    that: "vlan_id in vlan_list"
    msg: "VLAN does not exist. Please deploy first"

- name: "access VLAN {{ vlan_id }} on {{ interface }}"
  nxos_config:
    before: "default interface {{ interface }}"
    lines:
      - "description {{ port_description }}"
      - switchport
      - switchport mode access
      - “switchport access vlan {{ vlan_id }}”
      - no shutdown
    parents: "interface {{ interface }}"
    provider:
      timeout: 400
  when: interface not in pod_interconnects.keys()
