---
- nxos_command:
    commands: "show running-config interface {{interface}}"
  register: config_before

- name: Before State
  debug:
    msg: "{{ config_before.stdout_lines }}"

- nxos_config:
    lines:
      - default interface {{ interface }}
      - description default trunk
      - switchport
      - switchport mode trunk
      - no shut
    parents: "interface {{ interface }}"
    match: none

- nxos_command:
    commands: "show running-config interface {{interface}}"
  register: config_after

- name: After State
  debug:
    msg: "{{ config_after.stdout_lines }}"
