---
- nxos_command:
    commands: "show running-config interface {{interface}}"
    provider:
      timeout: 400
  register: config_before

- name: "Before State {{ interface }}"
  debug:
    msg: "{{ config_before.stdout_lines }}"

- nxos_config:
    before: "default interface {{ interface }}"
    lines:
      - description default trunk
      - switchport
      - switchport mode trunk
      - swtichport trunk allowed vlan none
      - no shut
    parents: "interface {{ interface }}"
    match: none
    provider:
      timeout: 400

- nxos_command:
    commands: "show running-config interface {{interface}}"
    provider:
      timeout: 400
  register: config_after

- name: "After State {{ interface }}"
  debug:
    msg: "{{ config_after.stdout_lines }}"
