---
- name: "default and shutdown {{ interface }}"
  nxos_config:
    before: "default interface {{ interface }}"
    lines:
      - shutdown
    parents: "interface {{ interface }}"
    provider:
      timeout: 400
  when: interface not in pod_interconnects.keys()
