---
- name: "show running-config interface {{interface}}"
  nxos_command:
    commands: "show running-config interface {{interface}}"
    provider:
      timeout: 400
  register: config_before

- name: "Before State {{ interface }}"
  debug:
    msg: "{{ config_before.stdout_lines }}"

- name: "default and configure {{ interface }} as a trunk "
  nxos_config:
    before: "default interface {{ interface }}"
    lines:
      - description default trunk
      - switchport
      - switchport mode trunk
      - switchport trunk allowed vlan none
      - no shutdown
    parents: "interface {{ interface }}"
    match: none
    provider:
      timeout: 400

- name: "show running-config interface {{interface}}"
  nxos_command:
    commands: "show running-config interface {{interface}}"
    provider:
      timeout: 400
  register: config_after

- name: "After State {{ interface }}"
  debug:
    msg: "{{ config_after.stdout_lines }}"
