---
- name: "configure vlan {{vlan_id}} from id"
  nxos_vlan:
    vlan_id: "{{ vlan_id }}"
    name: "{{ vlan_description }}"
    provider:
      timeout: 400

- name: "add vlan {{ vlan_id }} to {{ interface }}"
  nxos_config:
    lines:
      - "switchport trunk allowed vlan add {{ vlan_id}}"
    parents: "interface {{ interface }}"
    provider:
      timeout: 400
